server:
   port: 9850
mobile: 15289288565
project: qiusheng-web
spring:
   profiles:
      active: dev
   messages:
      basename: i18n/messages
      encoding: UTF-8
   data:
      elasticsearch:
         cluster-name: my-application
         cluster-nodes: 127.0.0.1:9300




